version: '2'

services:

  jobbuzz_zookeeper:
    image: wurstmeister/zookeeper
    container_name: jobbuzz_zookeeper
    ports:
      - 2181:2181
    volumes:
      - /data/jobbuzz_zookeeper/data:/opt/zookeeper-3.4.9/data
      - /data/jobbuzz_zookeeper/conf:/opt/zookeeper-3.4.9/conf

  jobbuzz_kafka:
    image: wurstmeister/kafka:0.10.2.0
    container_name: jobbuzz_kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: jobbuzz_kafka 
      KAFKA_ZOOKEEPER_CONNECT: jobbuzz_zookeeper:2181
    links:
      - jobbuzz_zookeeper
    volumes:
      - /data/jobbuzz_kafka:/var/lib/kafka
  
  jobbuzz_spark_master:
    image: gettyimages/spark:2.1.0-hadoop-2.7
    command: bin/spark-class org.apache.spark.deploy.master.Master -h jobbuzz_spark_master
    hostname: jobbuzz_spark_master
    container_name: jobbuzz_spark_master
    environment:
      MASTER: spark://jobbuzz_spark_master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 6066
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - /data/jobbuzz_spark/conf/master:/conf
      - /data/jobbuzz_spark/tmp/data:/tmp/data

  spark_worker:
    image: gettyimages/spark:2.1.0-hadoop-2.7
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://jobbuzz_spark_master:7077
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    links:
      - jobbuzz_spark_master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    volumes:
      - ~/data/jobbuzz_spark/conf/worker:/conf
      - ~/data/jobbuzz_spark/tmp/data:/tmp/data

  jobbuzz_zeppelin:
    image: xemuliam/zeppelin:0.7.0
    container_name: jobbuzz_zeppelin
    links:
      - jobbuzz_spark_master
    ports:
      - 3000:8080
      - 8443:8443
    volumes:
      - /data/jobbuzz_zeppelin/notebooks:/usr/zeppelin/notebook
      - /data/jobbuzz_zeppelin/data:/usr/zeppelin/data

  jobbuzz_twitter:
    build:
      context: twitter
    image: jobbuzz_twitter:latest
    container_name: jobbuzz_twitter
    links:
      - jobbuzz_zookeeper
      - jobbuzz_kafka
    environment:
      - TWITTER_CONSUMER_KEY:$TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET:$TWITTER_CONSUMER_SECRET
      - TWITTER_ACCESS_TOKEN:$TWITTER_ACCESS_TOKEN
      - TWITTER_TOKEN_SECRET:$TWITTER_TOKEN_SECRET

  jobbuzz_spark:
    build:
      context: spark
    image: jobbuzz_spark:latest
    container_name: jobbuzz_spark
    links:
      - jobbuzz_zookeeper
      - jobbuzz_kafka
    environment:
      - BUZZ_DIR_DATA:$BUZZ_DIR_DATA
      - BUZZ_DIR_CHECKPOINTS:$BUZZ_DIR_CHECKPOINTS

