version: '2'

services:
  # namenode:
  #   image: singularities/hadoop
  #   command: start-hadoop namenode
  #   hostname: namenode
  #   environment:
  #     HDFS_USER: buzz
  #   ports:
  #     - 8020:8020
  #     - 14000:14000
  #     - 50070:50070
  #     - 50075:50075
  #     - 10020:10020
  #     - 13562:13562
  #     - 19888:19888

  # datanode:
  #   image: singularities/hadoop
  #   command: start-hadoop datanode namenode
  #   environment:
  #     HDFS_USER: buzz
  #   links:
  #     - namenode

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:0.10.2.0
    container_name: kafka
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      CREATE_KAFKA_TOPICS: job-tweets:4:1
    ports:
      - 9092:9092
    links:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/data/jobbuzz_kafka:/var/lib/kafka
  
  sparkmaster:
    image: gettyimages/spark:2.1.0-hadoop-2.7
    command: bin/spark-class org.apache.spark.deploy.master.Master -h sparkmaster
    hostname: sparkmaster
    container_name: sparkmaster
    environment:
      MASTER: spark://sparkmaster:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
      BUZZ_DIR_DATA: $BUZZ_DIR_DATA
      BUZZ_DIR_CHECKPOINTS: $BUZZ_DIR_CHECKPOINTS
    links:
      - zookeeper
      - kafka
    expose:
      - 6066
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ~/data/jobbuzz_sparkmaster/conf/master:/conf
      - ~/data/jobbuzz_sparkmaster/tmp/data:/tmp/data
      - ~/data/jobbuzz_sparkmaster/data:/home/buzz/data

  sparkworker:
    image: gettyimages/spark:2.1.0-hadoop-2.7
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://sparkmaster:7077
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
      BUZZ_DIR_DATA: $BUZZ_DIR_DATA
      BUZZ_DIR_CHECKPOINTS: $BUZZ_DIR_CHECKPOINTS
    links:
      - sparkmaster
      - zookeeper
      - kafka
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8081
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ~/data/jobbuzz_sparkworker/conf/worker:/conf
      - ~/data/jobbuzz_sparkworker/tmp/data:/tmp/data
      - ~/data/jobbuzz_sparkworker/data:/home/buzz/data

  # jobbuzz_zeppelin:
  #   image: xemuliam/zeppelin:0.7.0
  #   container_name: jobbuzz_zeppelin
  #   links:
  #     - jobbuzz_spark_master
  #   ports:
  #     - 3000:8080
  #     - 8443:8443
  #   volumes:
  #     - ~/data/jobbuzz_zeppelin/notebooks:/usr/zeppelin/notebook
  #     - ~/data/jobbuzz_zeppelin/data:/usr/zeppelin/data

  jobbuzz_twitter:
    build:
      context: twitter
    container_name: jobbuzz_twitter
    links:
      - zookeeper
      - kafka
    environment:
      TWITTER_CONSUMER_KEY: $TWITTER_CONSUMER_KEY
      TWITTER_CONSUMER_SECRET: $TWITTER_CONSUMER_SECRET
      TWITTER_ACCESS_TOKEN: $TWITTER_ACCESS_TOKEN
      TWITTER_TOKEN_SECRET: $TWITTER_TOKEN_SECRET

  jobbuzz_spark:
    build:
      context: spark
    container_name: jobbuzz_spark
    links:
      - zookeeper
      - kafka
      - sparkmaster
      - sparkworker
    ports:
      - 4041:4040
    environment:
      BUZZ_MASTER: $BUZZ_MASTER
      BUZZ_DIR_DATA: $BUZZ_DIR_DATA
      BUZZ_DIR_CHECKPOINTS: $BUZZ_DIR_CHECKPOINTS
    volumes:
      - ~/data/jobbuzz_spark/data:/home/buzz/data

