version: '2'
services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: jobbuzz_zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    container_name: jobbuzz_zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: jobbuzz_zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/jobbuzz_kafka:/var/lib/kafka
  
  spark_master:
    image: gettyimages/spark:2.1.0-hadoop-2.7
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark_master
    hostname: spark_master
    container_name: jobbuzz_spark_master
    environment:
      MASTER: spark://spark_master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - /data/jobbuzz_spark/conf/master:/conf
      - /data/jobbuzz_spark/tmp/data:/tmp/data

  spark_worker:
    image: gettyimages/spark:2.1.0-hadoop-2.7
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark_master:7077
    hostname: spark_worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    links:
      - spark_master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    volumes:
      - ~/data/jobbuzz_spark/conf/worker:/conf
      - ~/data/jobbuzz_spark/tmp/data:/tmp/data
  zeppelin:
    image: xemuliam/zeppelin:0.7.0
    container_name: jobbuzz_zeppelin
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - /data/jobbuzz_zeppelin/notebooks:/usr/zeppelin/notebook
      - /data/jobbuzz_zeppelin/data:/usr/zeppelin/data
